import '@/lib/server/only';

export const ONRAMP_FAILURE_CODES = {
  QUOTE_EXPIRED: 'QUOTE_EXPIRED',
  PIX_PAID_AFTER_CHARGE_EXPIRED: 'PIX_PAID_AFTER_CHARGE_EXPIRED',
  RAMP_NOT_CONFIGURED: 'RAMP_NOT_CONFIGURED',
  INVALID_RAMP_AMOUNT: 'INVALID_RAMP_AMOUNT',
  INVALID_RAMP_CALLBACK_URL: 'INVALID_RAMP_CALLBACK_URL',
  INVALID_USDC_DELIVERY_AMOUNT: 'INVALID_USDC_DELIVERY_AMOUNT',
  BRH_SALE_PENDING_PERSIST_FAILED: 'BRH_SALE_PENDING_PERSIST_FAILED',
  BRH_SALE_SUBMIT_FAILED: 'BRH_SALE_SUBMIT_FAILED',
  BRH_SALE_FAILED: 'BRH_SALE_FAILED',
  BRH_SALE_INSUFFICIENT_FUNDS: 'BRH_SALE_INSUFFICIENT_FUNDS',
  BRH_SALE_NEEDS_REVIEW: 'BRH_SALE_NEEDS_REVIEW',
  BRH_SALE_CALLBACK_FAILED: 'BRH_SALE_CALLBACK_FAILED',
  USDC_DELIVERY_PENDING_PERSIST_FAILED: 'USDC_DELIVERY_PENDING_PERSIST_FAILED',
  USDC_DELIVERY_SUBMIT_FAILED: 'USDC_DELIVERY_SUBMIT_FAILED',
  USDC_DELIVERY_FAILED: 'USDC_DELIVERY_FAILED',
  USDC_DELIVERY_INSUFFICIENT_FUNDS: 'USDC_DELIVERY_INSUFFICIENT_FUNDS',
  USDC_DELIVERY_NEEDS_REVIEW: 'USDC_DELIVERY_NEEDS_REVIEW',
  USDC_DELIVERY_CALLBACK_FAILED: 'USDC_DELIVERY_CALLBACK_FAILED',
  FX_PREPARE_FAILED: 'FX_PREPARE_FAILED',
  FX_PERSIST_FAILED: 'FX_PERSIST_FAILED',
  FX_TRADE_FAILED: 'FX_TRADE_FAILED',
  BRH_REDEMPTION_RECORD_FAILED: 'BRH_REDEMPTION_RECORD_FAILED',
  WITHDRAW_PREPARE_FAILED: 'WITHDRAW_PREPARE_FAILED',
  WITHDRAW_CONFIG_MISSING: 'WITHDRAW_CONFIG_MISSING',
  WITHDRAW_PERSIST_FAILED: 'WITHDRAW_PERSIST_FAILED',
  WITHDRAW_REQUEST_FAILED: 'WITHDRAW_REQUEST_FAILED',
} as const;

export type OnrampFailureCode = (typeof ONRAMP_FAILURE_CODES)[keyof typeof ONRAMP_FAILURE_CODES];

export function buildOnrampFailurePatch(input: {
  code: OnrampFailureCode;
  reason: string;
  needsReview?: boolean;
}) {
  return {
    failure_code: input.code,
    failure_reason: input.reason,
    needs_review_reason: input.needsReview === false ? null : input.reason,
  } as const;
}

export function clearOnrampFailurePatch() {
  return {
    failure_code: null,
    failure_reason: null,
    needs_review_reason: null,
  } as const;
}
