// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://yzzvnomfjxzlsolzwkfd.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6enZub21manh6bHNvbHp3a2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg4MTYwMjAsImV4cCI6MjA5NDM5MjAyMH0.bzdkWTHRN-mAn4-pj59U1qmtnSzKKXvGEvP5tLYfbSE';

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
